/**
 * Writes the Uzbek Cyrillic interface texts from the Uzbek Latin ones. Run it after changing `src/core/locales/uz.ts`:
 * `node scripts/generate-uz-cyrl.mjs`. Node strips the TypeScript types of the imported sources itself.
 */
import { writeFileSync } from 'node:fs';

import { uz } from '../src/core/locales/uz.ts';
import { transliterate } from '../src/core/transliterate.ts';

/** Latin names and loanwords that keep their spelling in Cyrillic texts, or have an established Cyrillic form. */
const FIXES = [
  ['ҲТМЛ', 'HTML'],
  ['Wорд', 'Word'],
  ['(.доcх)', '(.docx)'],
  ['УРЛ', 'URL'],
  ['ПДФ', 'PDF'],
  ['(алт)', '(alt)'],
  ['Компютер', 'Компьютер'],
  ['Навигатсия', 'Навигация'],
  ['Cтрл+Энтер', 'Ctrl+Enter']
];

const convert = value =>
  FIXES.reduce((text, [from, to]) => text.replaceAll(from, to), transliterate(value, 'toCyrillic'));

const entries = Object.entries(uz).map(([key, value]) => `  '${key}': '${convert(value).replaceAll("'", "\\'")}'`);

writeFileSync(
  new URL('../src/core/locales/uz-cyrl.ts', import.meta.url),
  `import type { EditorLabelKey } from './uz';

/** Uzbek (Cyrillic) texts of the editor interface, generated by \`scripts/generate-uz-cyrl.mjs\`. */
export const uzCyrl: Readonly<Record<EditorLabelKey, string>> = {
${entries.join(',\n')}
};
`
);
